"""change data

Revision ID: f3781c65cbcd
Revises: cb4ac80b4f0b
Create Date: 2025-02-03 11:25:57.544823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3781c65cbcd'
down_revision: Union[str, None] = 'cb4ac80b4f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='Уникальное название проекта, обязательное строковое поле; Допустимая длина строки — от 1 до 150 символов включительно;',
               existing_comment='Уникальное название проекта, обязательное строковое поле; допустимая длина строки — от 1 до 150 символов включительно;',
               existing_nullable=False)
    op.alter_column('project', 'created_on',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Дата и время создания проекта.',
               existing_nullable=False)
    op.alter_column('project', 'base_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_comment='Путь до базовой директории, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;')
    op.alter_column('project', 'arch_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               comment='Путь до архивной директории, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;',
               existing_comment='Путь до файла, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;')
    op.alter_column('project', 'ftp_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_comment='Путь до файла, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'ftp_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_comment='Путь до файла, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;')
    op.alter_column('project', 'arch_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               comment='Путь до файла, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;',
               existing_comment='Путь до архивной директории, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;')
    op.alter_column('project', 'base_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_comment='Путь до базовой директории, обязательное строковое поле; допустимая длина строки — от 1 до 200 символов включительно;')
    op.alter_column('project', 'created_on',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Дата и время создания проекта.',
               existing_nullable=False)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='Уникальное название проекта, обязательное строковое поле; допустимая длина строки — от 1 до 150 символов включительно;',
               existing_comment='Уникальное название проекта, обязательное строковое поле; Допустимая длина строки — от 1 до 150 символов включительно;',
               existing_nullable=False)
    # ### end Alembic commands ###
