"""Create user

Revision ID: 9ea8adb51fb7
Revises: 78b631726424
Create Date: 2025-02-05 16:50:42.299429

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ea8adb51fb7"
down_revision: Union[str, None] = "78b631726424"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "phone_number",
            sa.String(length=18),
            nullable=False,
            comment="Номер пользователя, уникальное обязательное строковое поле; допустимая длина строки - от 7 до 18 символов включительно;",
        ),
        sa.Column(
            "first_name",
            sa.String(length=256),
            nullable=False,
            comment="Имя пользователя, обязательное строковое поле; допустимая длина строки - от 3 до 256 символов включительно;",
        ),
        sa.Column(
            "last_name",
            sa.String(length=256),
            nullable=False,
            comment="Фамилия пользователя, обязательное строковое поле; допустимая длина строки - от 3 до 256 символов включительно;",
        ),
        sa.Column(
            "email",
            sa.String(length=256),
            nullable=False,
            comment="email пользователя, уникальное обязательное строковое поле; допустимая длина строки - от 6 до 256 символов включительно;",
        ),
        sa.Column(
            "password",
            sa.String(),
            nullable=False,
            comment="Хешированный пароль пользователя, обязательное строковое поле;",
        ),
        sa.Column(
            "is_user",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Булево значение, определяющее зарегестрированного пользователя.",
        ),
        sa.Column(
            "is_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Булево значение, определяющее пользователя администратора.",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Булево значение, определяющее пользователя суперюзера.",
        ),
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Номер в базе данных",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
